// Main plan is to make main.cpp generated by the engine and not editable by user. Main should load setting and objects from scene and project files.

// CoreEngine
#include "Engine.hpp"
#include "components/GameInfo.hpp"
#include "components/errorUtils.hpp"
#include "components/ResolutionManager.hpp"
#include "components/InputSystem.hpp"
#include "components/SceneManager.hpp"

// Object System
#include "components/GameComponents/BasicComponents.hpp"
#include "components/GameComponents/InputComponent.hpp"
#include "components/GameObjects/Creators/ModelCreator.hpp"
#include "components/GameObjects/ModelObject.hpp"
#include "components/GameObjects/CameraObject.hpp"

#include "glm/fwd.hpp"

#include <cstdlib>
#include <memory>
#include <sys/types.h>

class ObjectTest : public vex::Engine {
public:
    using vex::Engine::Engine; // Inherit constructor
    bool animate = true;
    vex::SceneManager sceneManager;

    void processEvent(const SDL_Event& event, float deltaTime) {
        if (event.type == SDL_EVENT_KEY_DOWN) {
            const SDL_KeyboardEvent& key_event = event.key;

            // Physical key position (recommended for games)
            if (key_event.scancode == SDL_SCANCODE_ESCAPE) {
                m_running = false;
            }

            if (key_event.scancode == SDL_SCANCODE_P) {
                animate = !animate;
            }

            // Virtual key (respects keyboard layout)
            if (key_event.key == SDLK_ESCAPE) {
                m_running = false;
            }

            if (key_event.scancode == SDL_SCANCODE_1) {
                setResolutionMode(vex::ResolutionMode::NATIVE);
            }

            if (key_event.scancode == SDL_SCANCODE_2) {
                setResolutionMode(vex::ResolutionMode::PS1_SHARP);
            }

            if (key_event.scancode == SDL_SCANCODE_3) {
                setResolutionMode(vex::ResolutionMode::RES_240P);
            }

            if (key_event.scancode == SDL_SCANCODE_4) {
                setResolutionMode(vex::ResolutionMode::RES_480P);
            }
        }
    }

    vex::ModelObject* humanEntity1;
    vex::ModelObject* humanEntity2;
    vex::ModelObject* humanEntity3;
    vex::ModelObject* humanEntity4;
    vex::ModelObject* viperEntity1;
    vex::ModelObject* viperEntity2;
    vex::ModelObject* viperShadow1;
    vex::ModelObject* viperShadow2;
    vex::ModelObject* cube;

    double fps = 0;

    void beginGame() override {
        sceneManager.loadScene("Assets/scenes/main.json", *this);
        sceneManager.sceneBegin();

        m_vexUI->load("Assets/ui/example.json");

        m_vexUI->setText("score", "FPS: " + std::to_string(fps));
        m_vexUI->setOnClick("pause", []() {
            log("Pause button clicked");
        });

        vex::MeshComponent humanMesh = vex::createMeshFromPath("Assets/human.obj", *this);
        vex::TransformComponent humanTransform = vex::TransformComponent{
            glm::vec3{0.0f, 0.3f, 0.0f},
            glm::vec3{0.0f, 0.0f, 0.0f},
            glm::vec3{1.0f, 1.0f, 1.0f}};
        humanEntity1 = vex::createModelFromComponents("human1", humanMesh, humanTransform, *this);
        humanTransform.position += glm::vec3(0.5f,-0.3f,0);
        humanEntity2 = vex::createModelFromComponents("human2", humanMesh, humanTransform, *this);
        humanTransform.position += glm::vec3(0.5f,0,0);
        humanEntity3 = vex::createModelFromComponents("human3", humanMesh, humanTransform, *this);
        humanTransform.position += glm::vec3(0.5f,0,0);
        humanEntity4 = vex::createModelFromComponents("human4", humanMesh, humanTransform, *this);

        humanEntity2->ParentTo(humanEntity1->GetEntity());
        humanEntity3->ParentTo(humanEntity2->GetEntity());
        humanEntity4->ParentTo(humanEntity3->GetEntity());

        viperEntity1 = vex::createModelFromPath("Assets/scene.gltf", "viper1", *this);
        viperEntity2 = vex::createModelFromPath("Assets/scene.gltf", "viper2", *this);
        viperEntity2->GetComponent<vex::TransformComponent>().position += glm::vec3{2.0f, 0.0f, 0.0f};


        viperShadow1 = vex::createModelFromPath("Assets/ViperShadow.obj", "shadow1", *this);
        viperShadow1->GetComponent<vex::MeshComponent>().isTransparent = true;
        viperShadow1->GetComponent<vex::TransformComponent>().rotation += glm::vec3{0.0f, 90.0f, 0.0f};
        viperShadow1->GetComponent<vex::TransformComponent>().scale = glm::vec3{0.9f, 0.9f, 0.9f};
        viperShadow1->GetComponent<vex::TransformComponent>().position += glm::vec3{0.0f, -0.03f, 0.0f};
        viperShadow2 = vex::createModelFromPath("Assets/ViperShadow.obj", "shadow2", *this);
        viperShadow2->GetComponent<vex::MeshComponent>().isTransparent = true;
        viperShadow2->GetComponent<vex::TransformComponent>().rotation += glm::vec3{0.0f, 90.0f, 0.0f};
        viperShadow2->GetComponent<vex::TransformComponent>().scale = glm::vec3{0.9f, 0.9f, 0.9f};
        viperShadow2->GetComponent<vex::TransformComponent>().position += glm::vec3{2.0f, -0.03f, 0.0f};


        vex::MeshComponent cubeMesh = vex::createMeshFromPath("Assets/cube.obj", *this);
        vex::TransformComponent cubeTransform = vex::TransformComponent{
            glm::vec3{-4.0f, -1.61f, -5.0f},
            glm::vec3{0.0f, 0.0f, 0.0f},
            glm::vec3{10.0f, 1.0f, 10.0f}};
        cube = vex::createModelFromComponents("cube", cubeMesh, cubeTransform, *this);
#if DEBUG
        m_imgui->addUIFunction([this]() {
            ImGui::Begin("Engine Stats");
            ImGui::Text("Renderer: Vulkan");
            ImGui::Text("FPS: %i", (int)fps);
            ImGui::Text("Current frame: %i", (int)m_frame);
            ImGui::Text("Render resolution: %ix%i", (int)this->m_resolutionManager->getRenderResolution().x, (int)this->m_resolutionManager->getRenderResolution().y);
            ImGui::Text("Window resolution: %ix%i", (int)this->m_resolutionManager->getWindowResolution().x, (int)this->m_resolutionManager->getWindowResolution().y);
            ImGui::End();
        });
#endif
    }

    void update(float deltaTime) override {

        fps = 1/deltaTime;

        m_vexUI->setText("score", "FPS: " + std::to_string(fps));

        sceneManager.sceneUpdate(deltaTime);

        //pass
        if (humanEntity1 && humanEntity1->isValid()) {
            humanEntity1->GetComponent<vex::TransformComponent>().rotation.y = m_frame;
        }

        // testing if i can remove entities at runtime
        if (m_frame == 120000 && humanEntity1 && humanEntity1->isValid()) {
            delete humanEntity1;
            humanEntity1 = nullptr;
        }
        if (m_frame == 240000 && humanEntity2 && humanEntity2->isValid()) {
            delete humanEntity2;
            humanEntity2 = nullptr;
        }
        if (m_frame == 360000 && humanEntity3 && humanEntity3->isValid()) {
            delete humanEntity3;
            humanEntity3 = nullptr;
        }
        if (m_frame == 480000 && humanEntity4 && humanEntity4->isValid()) {
            delete humanEntity4;
            humanEntity4 = nullptr;
        }
        if (m_frame == 160000 && viperEntity1 && viperEntity1->isValid()) {
            delete viperEntity1;
            viperEntity1 = nullptr;
        }
        if (m_frame == 320000 && viperEntity2 && viperEntity2->isValid()) {
            delete viperEntity2;
            viperEntity2 = nullptr;
        }
    }

    void render() override {
        // Custom rendering if needed
        Engine::render(); // Call base render
    }
};

int main(int argc, char* argv[]) {
    try {
        log("Creating game instance...");

        vex::GameInfo gInfo{"ObjectTest",
                            0,
                            1,
                            0
        };
        ObjectTest game("ObjectTest", 1280, 720, gInfo);

        log("Game instance created successfully");
        log("Starting game loop...");
        game.run();
        log("Game loop exited normally");
    } catch (const std::exception& e) {
        SDL_LogError(SDL_LOG_CATEGORY_ERROR, "Game error:");
        handle_exception(e);
        return 1;
    } catch (...) {
        SDL_LogError(SDL_LOG_CATEGORY_ERROR, "Unknown error occurred");
        return 1;
    }

    log("Exiting cleanly");
    return 0;
}
