// Main plan is to make main.cpp generated by the engine and not editable by user. Main should load setting and objects from scene and project files.
#include "components/GameObjects/GameObject.hpp"
#define SDL_MAIN_HANDLED
// CoreEngine
#include "Engine.hpp"
#include "components/GameInfo.hpp"
#include "components/errorUtils.hpp"
#include "components/ResolutionManager.hpp"
#include "components/InputSystem.hpp"
#include "components/SceneManager.hpp"
#include "components/PhysicsSystem.hpp"

// Object System
#include "components/GameComponents/BasicComponents.hpp"
#include "components/GameComponents/InputComponent.hpp"
#include "components/GameObjects/Creators/ModelCreator.hpp"
#include "components/GameObjects/ModelObject.hpp"
#include "components/GameObjects/CameraObject.hpp"

#include "glm/fwd.hpp"

#include <cstdlib>
#include <memory>
#include <sys/types.h>

class ObjectTest : public vex::Engine {
public:
    using vex::Engine::Engine; // Inherit constructor
    bool animate = true;

    void processEvent(const SDL_Event& event, float deltaTime) {
        if (event.type == SDL_EVENT_KEY_DOWN) {
            const SDL_KeyboardEvent& key_event = event.key;

            // Physical key position (recommended for games)
            #ifdef DEBUG
            if (key_event.scancode == SDL_SCANCODE_ESCAPE) {
                m_running = false;
            }
            #endif

            if (key_event.scancode == SDL_SCANCODE_P) {
                animate = !animate;
            }

            // Virtual key (respects keyboard layout)
            if (key_event.key == SDLK_ESCAPE) {
                m_running = false;
            }

            if (key_event.scancode == SDL_SCANCODE_1) {
                setResolutionMode(vex::ResolutionMode::NATIVE);
            }

            if (key_event.scancode == SDL_SCANCODE_2) {
                setResolutionMode(vex::ResolutionMode::PS1_SHARP);
            }

            if (key_event.scancode == SDL_SCANCODE_3) {
                setResolutionMode(vex::ResolutionMode::RES_240P);
            }

            if (key_event.scancode == SDL_SCANCODE_4) {
                setResolutionMode(vex::ResolutionMode::RES_480P);
            }
        }
    }

    vex::ModelObject* humanEntity1;
    vex::ModelObject* humanEntity2;
    vex::ModelObject* humanEntity3;
    vex::ModelObject* humanEntity4;
    vex::ModelObject* viperEntity1;
    vex::ModelObject* viperEntity2;
    vex::ModelObject* viperShadow1;
    vex::ModelObject* viperShadow2;
    vex::ModelObject* cube;
    vex::ModelObject* cube2;
    vex::ModelObject* cube3;
    vex::ModelObject* cube4;

    vex::GameObject* testLight = new vex::GameObject(*this, "TestLight");

    double fps = 0;

    void beginGame() override {
        getSceneManager()->loadScene("Assets/scenes/main.json", *this);

        vex::MeshComponent humanMesh = vex::createMeshFromPath("Assets/human.obj", *this);
        vex::TransformComponent humanTransform = vex::TransformComponent{
            getRegistry(),
            glm::vec3{0.0f, 0.3f, 0.0f},
            glm::vec3{0.0f, 0.0f, 0.0f},
            glm::vec3{1.0f, 1.0f, 1.0f}};
        //vex::PhysicsComponent humanPhysics = vex::PhysicsComponent::Mesh(humanMesh, vex::BodyType::KINEMATIC);
        vex::PhysicsComponent humanPhysics = vex::PhysicsComponent::Box({0.5f, 1.0f, 0.1f}, vex::BodyType::KINEMATIC);

        humanEntity1 = vex::createModelFromComponents("human1", humanMesh, humanTransform, *this);
        humanTransform.addLocalPosition(glm::vec3(1.0f,-0.3f,0));
        humanEntity2 = vex::createModelFromComponents("human2", humanMesh, humanTransform, *this);
        //humanTransform.addLocalPosition(glm::vec3(0.5f,0,0));
        humanEntity3 = vex::createModelFromComponents("human3", humanMesh, humanTransform, *this);
        //humanTransform.addLocalPosition(glm::vec3(0.5f,0,0));
        humanEntity4 = vex::createModelFromComponents("human4", humanMesh, humanTransform, *this);

        humanEntity2->ParentTo(humanEntity1->GetEntity());
        humanEntity3->ParentTo(humanEntity2->GetEntity());
        humanEntity4->ParentTo(humanEntity3->GetEntity());

        humanEntity1->AddComponent(humanPhysics);
        humanEntity2->AddComponent(humanPhysics);
        humanEntity3->AddComponent(humanPhysics);
        humanEntity4->AddComponent(humanPhysics);

        viperEntity1 = vex::createModelFromPath("Assets/scene.gltf", "viper1", *this);
        viperEntity2 = vex::createModelFromPath("Assets/scene.gltf", "viper2", *this);
        viperEntity2->GetComponent<vex::TransformComponent>().addLocalPosition(glm::vec3{2.0f, 0.0f, 0.0f});

        vex::PhysicsComponent viperPhysics = vex::PhysicsComponent::Mesh(viperEntity1->GetComponent<vex::MeshComponent>(), vex::BodyType::STATIC);

        viperEntity1->AddComponent(viperPhysics);
        viperEntity2->AddComponent(viperPhysics);


        viperShadow1 = vex::createModelFromPath("Assets/ViperShadow.obj", "shadow1", *this);
        viperShadow1->GetComponent<vex::MeshComponent>().renderType = vex::RenderType::TRANSPARENT;
        viperShadow1->GetComponent<vex::TransformComponent>().addLocalRotation(glm::vec3{0.0f, 90.0f, 0.0f});
        viperShadow1->GetComponent<vex::TransformComponent>().setLocalScale(glm::vec3{0.9f, 0.9f, 0.9f});
        viperShadow1->GetComponent<vex::TransformComponent>().addLocalPosition(glm::vec3{0.0f, -0.03f, 0.0f});
        viperShadow2 = vex::createModelFromPath("Assets/ViperShadow.obj", "shadow2", *this);
        viperShadow2->GetComponent<vex::MeshComponent>().renderType = vex::RenderType::TRANSPARENT;
        viperShadow2->GetComponent<vex::TransformComponent>().addLocalRotation(glm::vec3{0.0f, 90.0f, 0.0f});
        viperShadow2->GetComponent<vex::TransformComponent>().setLocalScale(glm::vec3{0.9f, 0.9f, 0.9f});
        viperShadow2->GetComponent<vex::TransformComponent>().addLocalPosition(glm::vec3{2.0f, -0.03f, 0.0f});



        vex::MeshComponent floorCubeMesh = vex::createMeshFromPath("Assets/floorCube.obj", *this);
        vex::TransformComponent cubeTransform = vex::TransformComponent{
            getRegistry(),
            glm::vec3{0.5f, -1.1f, 0.0f},
            glm::vec3{0.0f, 0.0f, 0.0f},
            glm::vec3{5.0f, 0.5f, 5.0f}};
        cube = vex::createModelFromComponents("cube", floorCubeMesh, cubeTransform, *this);
        vex::PhysicsComponent cubePhysics = vex::PhysicsComponent::Box({5.0f, 0.5f, 5.0f}, vex::BodyType::STATIC);

        cubePhysics.addCollisionEnterBinding([this](entt::entity self, entt::entity other, const vex::CollisionHit& hit) {
            log("Hit at (%f, %f, %f)", hit.position.x, hit.position.y, hit.position.z);
        });
        cubePhysics.addCollisionStayBinding([this](entt::entity self, entt::entity other, const vex::CollisionHit& hit) {
            log("Still touching");
        });
        cubePhysics.addCollisionExitBinding([this](entt::entity self, entt::entity other) {
            log("Stopped touching");
        });

        cube->AddComponent(cubePhysics);

        vex::MeshComponent cubeMesh = vex::createMeshFromPath("Assets/cube.obj", *this);

        vex::TransformComponent cube2Transform = vex::TransformComponent{
            getRegistry(),
            glm::vec3{1.0f, 10.0f, 1.0f},
            glm::vec3{0.0f, 0.0f, 0.0f},
            glm::vec3{0.5f, 0.5f, 0.5f}};
        cube2 = vex::createModelFromComponents("cube2", cubeMesh, cube2Transform, *this);
        vex::PhysicsComponent cube2Physics = vex::PhysicsComponent::Box({0.5f, 0.5f, 0.5f}, vex::BodyType::DYNAMIC);
        cube2->AddComponent(cube2Physics);

        cube2Transform.addLocalPosition(glm::vec3{0.25f, 3.0f, 0.0f});
        cube2Transform.setLocalRotation(glm::vec3{-30.0f, 45.0f, 5.0f});
        cube3 = vex::createModelFromComponents("cube3", cubeMesh, cube2Transform, *this);
        cube3->AddComponent(cube2Physics);

        cube2Transform.addLocalPosition(glm::vec3{-0.5f, 3.0f, 0.2f});
        cube2Transform.setLocalRotation(glm::vec3{15.0f, 15.0f, 30.0f});
        cube4 = vex::createModelFromComponents("cube4", cubeMesh, cube2Transform, *this);
        cube4->AddComponent(cube2Physics);

        vex::InputComponent inputComp;
        inputComp.addBinding(SDL_SCANCODE_SPACE, vex::InputActionState::Held, [this](float deltaTime) {
            //GetComponent<vex::TransformComponent>().position += GetComponent<vex::TransformComponent>().getForwardVector(m_engine.getRegistry()) * (deltaTime * 2);
            getPhysicsSystem()->AddImpulse(cube4->GetComponent<vex::PhysicsComponent>().bodyId, glm::vec3(0.0f, 0.1f, 0.0f));
        });
        cube4->AddComponent(inputComp);

        testLight->AddComponent(vex::TransformComponent{m_registry});
        testLight->GetComponent<vex::TransformComponent>().addLocalPosition({1, 1.5f, 0});

        vex::LightComponent lightComp;
        lightComp.color = glm::vec3(1.0f, 0.0f, 1.0f);
        lightComp.intensity = 1.0f;
        lightComp.radius = 15.0f;
        testLight->AddComponent(lightComp);

#if DEBUG
        m_imgui->addUIFunction([this]() {
            ImGui::Begin("Engine Stats");
            ImGui::Text("Renderer: Vulkan");
            ImGui::Text("FPS: %i", (int)fps);
            ImGui::Text("Current frame: %i", (int)m_frame);
            ImGui::Text("Render resolution: %ix%i", (int)this->m_resolutionManager->getRenderResolution().x, (int)this->m_resolutionManager->getRenderResolution().y);
            ImGui::Text("Window resolution: %ix%i", (int)this->m_resolutionManager->getWindowResolution().x, (int)this->m_resolutionManager->getWindowResolution().y);
            ImGui::End();
        });
#endif
    }

    void update(float deltaTime) override {

        fps = 1/deltaTime;

        //pass
        if (humanEntity1 && humanEntity1->isValid()) {
            humanEntity1->GetComponent<vex::TransformComponent>().addYaw(25*deltaTime);
        }

        // testing if i can remove entities at runtime
        if (m_frame == 120000 && humanEntity1 && humanEntity1->isValid()) {
            delete humanEntity1;
            humanEntity1 = nullptr;
        }
        if (m_frame == 240000 && humanEntity2 && humanEntity2->isValid()) {
            delete humanEntity2;
            humanEntity2 = nullptr;
        }
        if (m_frame == 360000 && humanEntity3 && humanEntity3->isValid()) {
            delete humanEntity3;
            humanEntity3 = nullptr;
        }
        if (m_frame == 480000 && humanEntity4 && humanEntity4->isValid()) {
            delete humanEntity4;
            humanEntity4 = nullptr;
        }
        if (m_frame == 160000 && viperEntity1 && viperEntity1->isValid()) {
            delete viperEntity1;
            viperEntity1 = nullptr;
        }
        if (m_frame == 320000 && viperEntity2 && viperEntity2->isValid()) {
            delete viperEntity2;
            viperEntity2 = nullptr;
        }
    }

    void render() override {
        // Custom rendering if needed
        Engine::render(); // Call base render
    }
};

int main(int argc, char* argv[]) {
    try {
        log("Creating game instance...");

        vex::GameInfo gInfo{"ObjectTest",
                            0,
                            1,
                            0
        };
        ObjectTest game("ObjectTest", 1280, 720, gInfo);

        log("Game instance created successfully");
        log("Starting game loop...");
        game.run();
        log("Game loop exited normally");
    } catch (const std::exception& e) {
        SDL_LogError(SDL_LOG_CATEGORY_ERROR, "Game error:");
        handle_exception(e);
        return 1;
    } catch (...) {
        SDL_LogError(SDL_LOG_CATEGORY_ERROR, "Unknown error occurred");
        return 1;
    }

    log("Exiting cleanly");
    return 0;
}
