// Main plan is to make main.cpp generated by the engine and not editable by user. Main should load setting and objects from scene and project files.
#define SDL_MAIN_HANDLED
// CoreEngine
#include "Engine.hpp"
#include "components/GameInfo.hpp"
#include "components/errorUtils.hpp"
#include "components/ResolutionManager.hpp"
#include "components/InputSystem.hpp"
#include "components/SceneManager.hpp"

// Object System
#include "components/GameComponents/BasicComponents.hpp"
#include "components/GameComponents/InputComponent.hpp"
#include "components/GameObjects/Creators/ModelCreator.hpp"
#include "components/GameObjects/ModelObject.hpp"
#include "components/GameObjects/CameraObject.hpp"

#include "glm/fwd.hpp"

#include <cstdlib>
#include <memory>
#include <sys/types.h>

class PhysicsTest : public vex::Engine {
public:
    using vex::Engine::Engine; // Inherit constructor

    void processEvent(const SDL_Event& event, float deltaTime) {
        if (event.type == SDL_EVENT_KEY_DOWN) {
            const SDL_KeyboardEvent& key_event = event.key;

            if (key_event.scancode == SDL_SCANCODE_1) {
                setResolutionMode(vex::ResolutionMode::NATIVE);
            }

            if (key_event.scancode == SDL_SCANCODE_2) {
                setResolutionMode(vex::ResolutionMode::PS1_SHARP);
            }

            if (key_event.scancode == SDL_SCANCODE_3) {
                setResolutionMode(vex::ResolutionMode::RES_240P);
            }

            if (key_event.scancode == SDL_SCANCODE_4) {
                setResolutionMode(vex::ResolutionMode::RES_480P);
            }
        }
    }

    double fps = 0;

    void beginGame() override {
        getSceneManager()->loadScene("Assets/scenes/main.json", *this);
    }

    void update(float deltaTime) override {
        getSceneManager()->scenesUpdate(deltaTime);
    }

    void render() override {
        Engine::render();
    }
};

int main(int argc, char* argv[]) {
    try {
        log("Creating game instance...");

        vex::GameInfo gInfo{"PhysicsTest",
                            0,
                            1,
                            0
        };
        PhysicsTest game("PhysicsTest", 1280, 720, gInfo);

        log("Game instance created successfully");
        log("Starting game loop...");
        game.run();
        log("Game loop exited normally");
    } catch (const std::exception& e) {
        SDL_LogError(SDL_LOG_CATEGORY_ERROR, "Game error:");
        handle_exception(e);
        return 1;
    } catch (...) {
        SDL_LogError(SDL_LOG_CATEGORY_ERROR, "Unknown error occurred");
        return 1;
    }

    log("Exiting cleanly");
    return 0;
}
